version: '3.4'

volumes:
    bankAccounts:

services:

    bankaccounts.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        ports:
            - "80"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    sql_server:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: ${DOCKER_REGISTRY-}sql_server
        user: root
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrong(!)Password
        ports:
             - 8765:1433
        volumes:
            -  bankAccounts:/var/opt/mssql/data
            -  bankAccounts:/var/opt/mssql/backups

    activemq:
        image: islandora/activemq:main
        ports:
            - 8768:8161
            - 8769:61616

    rabbitmq:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - 8770:5672

    redis:
        image: redis:latest
        ports:
            - 8771:6379

    smtp:
        image: jijiechen/papercut:latest
        ports:
            - "8772:25"
            - 37408:37408