name: Shared Kernel CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dotnet-version: [ '8.0.X' ]

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./SharedKernel.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore ./SharedKernel.sln
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java version
        run: java -version

      - name: Download SonarScanner
        run: |
          curl -sSLo sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonarscanner.zip

      - name: Run Sonar Scanner
        run: ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
          projectKey: pipoburgos_SharedKernel
          organization: pipoburgos
      - name: Test
        run: dotnet test --no-restore --verbosity normal ./SharedKernel.sln
      - name: Pack
        run: dotnet pack --configuration Release --no-restore -ignore:.sln,.dcproj ./SharedKernel.sln
      - name: Prep packages
        run: dotnet nuget add source --username pipoburgos --password ${{ secrets.NUGET_PASSWORD }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pipoburgos/index.json"
      - name: Publish to GitHub packages 
        run: dotnet nuget push src/*/bin/Release/*.nupkg --api-key ${{ secrets.API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
